version: '3.7'

services:
  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    env_file:
      - ./.env.dev.db
  # This service simply builds the base image for the project used by both the webserver
  # and the DB setup commands
  web_python_image:
    build: ./services/web
    image: wedding-python
    env_file:
      - ./.env.dev.db
      - ./.env.dev
  db_create:
    image: wedding-python
    entrypoint: /usr/src/app/wait_for_db.sh
    command: python manage.py create_db
    volumes:
      - ./services/web/:/usr/src/app/
    env_file:
      - ./.env.dev.db
      - ./.env.dev
    depends_on:
      - db
      - web_python_image
  web:
    image: wedding-python
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev.db
      - ./.env.dev
    environment:
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      GOOGLE_MAPS_API_TOKEN: ${GOOGLE_MAPS_API_TOKEN}
    depends_on:
      - db_create
